import { take, mergeMap, catchError, throwError } from 'rxjs';
import { BlockNotPinnedError } from '../errors.mjs';
import { withOperationInaccessibleRetry } from './operation-inaccessible-retry.mjs';

const dynamicBlocks = /* @__PURE__ */ new Set(["best", "finalized", null]);
const getWithOptionalHash$ = (finalized$, best$, usingBlock) => {
  return (fn) => (hash, ...args) => {
    if (!dynamicBlocks.has(hash))
      return withOperationInaccessibleRetry(fn(hash, ...args)).pipe(
        usingBlock(hash)
      );
    const hash$ = hash === "best" ? best$ : finalized$;
    const result$ = hash$.pipe(
      take(1),
      mergeMap((h) => fn(h, ...args).pipe(usingBlock(h))),
      catchError((e) => {
        return e instanceof BlockNotPinnedError ? result$ : throwError(() => e);
      })
    );
    return withOperationInaccessibleRetry(result$);
  };
};

export { getWithOptionalHash$ };
//# sourceMappingURL=optionalHash.mjs.map
